// flow-typed signature: c65580cbcfe6586074a5ed1dace2939f
// flow-typed version: <<STUB>>/node-osascript_v^2.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-osascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-osascript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-osascript/demos/externalFile/demo' {
  declare module.exports: any;
}

declare module 'node-osascript/demos/injectvariables/demos' {
  declare module.exports: any;
}

declare module 'node-osascript/demos/simpleDialog/dialog' {
  declare module.exports: any;
}

declare module 'node-osascript/lib/index' {
  declare module.exports: any;
}

declare module 'node-osascript/lib/osa-parser' {
  declare module.exports: any;
}

declare module 'node-osascript/lib/osa-vargen' {
  declare module.exports: any;
}

declare module 'node-osascript/tests/independent/osaparser_test' {
  declare module.exports: any;
}

declare module 'node-osascript/tests/independent/osavargen_test' {
  declare module.exports: any;
}

declare module 'node-osascript/tests/osascript_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-osascript/demos/externalFile/demo.js' {
  declare module.exports: $Exports<'node-osascript/demos/externalFile/demo'>;
}
declare module 'node-osascript/demos/injectvariables/demos.js' {
  declare module.exports: $Exports<'node-osascript/demos/injectvariables/demos'>;
}
declare module 'node-osascript/demos/simpleDialog/dialog.js' {
  declare module.exports: $Exports<'node-osascript/demos/simpleDialog/dialog'>;
}
declare module 'node-osascript/lib/index.js' {
  declare module.exports: $Exports<'node-osascript/lib/index'>;
}
declare module 'node-osascript/lib/osa-parser.js' {
  declare module.exports: $Exports<'node-osascript/lib/osa-parser'>;
}
declare module 'node-osascript/lib/osa-vargen.js' {
  declare module.exports: $Exports<'node-osascript/lib/osa-vargen'>;
}
declare module 'node-osascript/tests/independent/osaparser_test.js' {
  declare module.exports: $Exports<'node-osascript/tests/independent/osaparser_test'>;
}
declare module 'node-osascript/tests/independent/osavargen_test.js' {
  declare module.exports: $Exports<'node-osascript/tests/independent/osavargen_test'>;
}
declare module 'node-osascript/tests/osascript_test.js' {
  declare module.exports: $Exports<'node-osascript/tests/osascript_test'>;
}
